import { PortfolioData } from './types';

export const initialPortfolioData: PortfolioData = {
  profile: {
    id: 'profile-1',
    name: 'Dhananjay C. Moundekar',
    greeting: "Hi, I'm Dhananjay 👋",
    headline: 'AI Developer | Full Stack Engineer | Data Scientist',
    short_intro:
      'Building AI-powered tools and scalable full-stack applications. Final-year AI student at PJLCE Nagpur & pursuing B.S. in Data Science at IIT Madras.',
    profile_image_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600', // Polished default portrait
    primary_cta_text: 'View Projects',
    primary_cta_link: '#projects',
    secondary_cta_text: 'Contact Me',
    secondary_cta_link: '#contact',
    email: 'dhanjanjaymoundekar1244@gmail.com',
    phone: '+91 7875654030',
    location: 'Nagpur, Maharashtra, India',
  },
  about: {
    id: 'about-1',
    title: 'Driven by AI Innovation & Seamless User Experiences',
    story:
      'I am a final-year Artificial Intelligence student at Priyadarshini J. L. College of Engineering (PJLCE), Nagpur, concurrently pursuing a B.S. in Data Science from IIT Madras. I specialize in bridging advanced Machine Learning / Natural Language Processing models with clean, performant full-stack web applications. Outside of code, I enjoy exploring geopolitics, historical events, and aviation developments.',
    education_summary: 'B.Tech in Artificial Intelligence (PJLCE) & B.S. in Data Science (IIT Madras)',
    current_status: 'Open to Full-time AI / Software Engineering Roles & Internships',
    career_interests: 'AI Engineering, Full Stack Web Development, NLP Pipelines, Scalable Systems',
    location: 'Nagpur / Remote',
  },
  certificates: [
    {
      id: 'cert-1',
      title: 'Technical Presentation 1st Rank Award',
      issuer: 'Priyadarshini J. L. College of Engineering (PJLCE), Nagpur',
      issue_date: '2024',
      description: 'Secured 1st place in the university-level technical presentation showcasing AI-based smart applications.',
      image_url: 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?auto=format&fit=crop&q=80&w=600',
      certificate_url: '#',
      sort_order: 1,
      is_published: true,
    },
    {
      id: 'cert-2',
      title: 'AI & Data Science Research Presentation',
      issuer: 'Indian Institute of Technology Madras (IIT Madras)',
      issue_date: '2024',
      description: 'Presented research on NLP-driven summarization and depth-mapped AI learning platforms at the IIT Madras Symposium.',
      image_url: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=600',
      certificate_url: '#',
      sort_order: 2,
      is_published: true,
    },
  ],
  skills: [
    { id: 'sk-1', name: 'Python', category: 'Programming', proficiency_percent: 95, sort_order: 1, is_published: true },
    { id: 'sk-2', name: 'JavaScript / TypeScript', category: 'Programming', proficiency_percent: 90, sort_order: 2, is_published: true },
    { id: 'sk-3', name: 'SQL', category: 'Programming', proficiency_percent: 85, sort_order: 3, is_published: true },
    
    { id: 'sk-4', name: 'PyTorch & Hugging Face GPT', category: 'AI / Machine Learning', proficiency_percent: 88, sort_order: 1, is_published: true },
    { id: 'sk-5', name: 'scikit-learn', category: 'AI / Machine Learning', proficiency_percent: 90, sort_order: 2, is_published: true },
    { id: 'sk-6', name: 'Transformers & NLP', category: 'AI / Machine Learning', proficiency_percent: 85, sort_order: 3, is_published: true },
    
    { id: 'sk-7', name: 'Exploratory Data Analysis (EDA)', category: 'Data Engineering', proficiency_percent: 92, sort_order: 1, is_published: true },
    { id: 'sk-8', name: 'Pandas & NumPy', category: 'Data Engineering', proficiency_percent: 94, sort_order: 2, is_published: true },
    
    { id: 'sk-9', name: 'React & Next.js', category: 'Web Development', proficiency_percent: 92, sort_order: 1, is_published: true },
    { id: 'sk-10', name: 'Node.js & Express', category: 'Web Development', proficiency_percent: 88, sort_order: 2, is_published: true },
    { id: 'sk-11', name: 'Tailwind CSS', category: 'Web Development', proficiency_percent: 95, sort_order: 3, is_published: true },
    
    { id: 'sk-12', name: 'MongoDB', category: 'Databases', proficiency_percent: 85, sort_order: 1, is_published: true },
    { id: 'sk-13', name: 'PostgreSQL & Supabase', category: 'Databases', proficiency_percent: 88, sort_order: 2, is_published: true },
    
    { id: 'sk-14', name: 'Git & GitHub', category: 'Tools & Technologies', proficiency_percent: 92, sort_order: 1, is_published: true },
    { id: 'sk-15', name: 'OpenStreetMap API', category: 'Tools & Technologies', proficiency_percent: 82, sort_order: 2, is_published: true },
    { id: 'sk-16', name: 'Cloudinary / Storage', category: 'Tools & Technologies', proficiency_percent: 85, sort_order: 3, is_published: true },
  ],
  projects: [
    {
      id: 'proj-1',
      title: 'Virtual Memory Palace — AI Educational Platform',
      slug: 'virtual-memory-palace',
      short_desc: 'Converts audio, video, and text into structured AI summaries and immersive 3D learning scenes.',
      detailed_desc:
        'An innovative learning platform leveraging Hugging Face GPT, Shap-E, and Blender to transform complex learning material into interactive 3D memory palaces.',
      problem_statement: 'Students struggle to absorb dense text and lengthy lecture recordings efficiently.',
      solution_statement: 'Integrated NLP summarization pipelines with 3D scene generation to convert key concepts into spatial visual cues.',
      contribution: 'Architected the end-to-end NLP text summarization engine, Shap-E model bindings, and React frontend interface.',
      image_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=800',
      github_url: 'https://github.com/dhananjay97mki',
      live_demo_url: '#',
      tech_stack: ['Python', 'React', 'Hugging Face GPT', 'Shap-E', 'Blender', 'Tailwind CSS'],
      category: 'AI & ML',
      featured: true,
      sort_order: 1,
      is_published: true,
      date: '2024',
    },
    {
      id: 'proj-2',
      title: 'Scalable Video Sharing & Streaming Platform',
      slug: 'video-sharing-app',
      short_desc: 'Scalable video streaming platform with JWT auth, chunked uploads, HLS streaming, and nested comments.',
      detailed_desc:
        'A comprehensive full-stack video platform featuring secure chunked video uploading via Cloudinary, HLS adaptive bitrate streaming, JWT user auth, threaded comments, and full text search.',
      problem_statement: 'Handling high-resolution video uploads and smooth streaming across variable network speeds without server strain.',
      solution_statement: 'Implemented chunked uploads and HLS video transcode pipelines paired with a MongoDB indexing strategy for rapid search.',
      contribution: 'Built the complete backend Node.js API, MongoDB database schema, JWT auth middleware, and React video player component.',
      image_url: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&q=80&w=800',
      github_url: 'https://github.com/dhananjay97mki',
      live_demo_url: '#',
      tech_stack: ['React', 'Node.js', 'Express', 'MongoDB', 'Cloudinary', 'JWT'],
      category: 'Full Stack',
      featured: true,
      sort_order: 2,
      is_published: true,
      date: '2024',
    },
    {
      id: 'proj-3',
      title: 'Student Growth & Exam Prediction System',
      slug: 'student-growth-prediction',
      short_desc: 'Predicts student exam performance and suggests personalized score benchmarks with 78% accuracy.',
      detailed_desc:
        'Machine learning application that analyzes historical student performance trends, attendance metrics, and test scores to predict upcoming exam outcomes and recommend elective courses.',
      problem_statement: 'Academic advisors lack predictive insights to identify at-risk students prior to final examinations.',
      solution_statement: 'Trained regression and classification models in scikit-learn on historical student records achieving ~78% accuracy.',
      contribution: 'Processed feature engineering datasets, evaluated ML models, and developed an interactive dashboard in React.',
      image_url: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&q=80&w=800',
      github_url: 'https://github.com/dhananjay97mki',
      live_demo_url: '#',
      tech_stack: ['Python', 'scikit-learn', 'React', 'Pandas', 'FastAPI'],
      category: 'Data Science',
      featured: true,
      sort_order: 3,
      is_published: true,
      date: '2023',
    },
    {
      id: 'proj-4',
      title: 'Alumni Connection & Real-Time Location App',
      slug: 'alumni-realtime-connection',
      short_desc: 'Mentorship networking platform with opt-in live location sharing, proximity alerts, and ETA tracking.',
      detailed_desc:
        'A real-time mobile/web networking platform connecting university seniors and alumni with students, featuring opt-in OpenStreetMap geo-tracking and automated proximity alerts for campus meetups.',
      problem_statement: 'Students face difficulties connecting with alumni during offline conferences and career expos.',
      solution_statement: 'Integrated OpenStreetMap geospatial queries with WebSocket real-time updates for location-aware networking.',
      contribution: 'Designed geospatial queries, map interface integration, and privacy-first opt-in location controls.',
      image_url: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=800',
      github_url: 'https://github.com/dhananjay97mki',
      live_demo_url: '#',
      tech_stack: ['React', 'Node.js', 'OpenStreetMap', 'WebSockets', 'Express'],
      category: 'Mobile & Realtime',
      featured: false,
      sort_order: 4,
      is_published: true,
      date: '2024',
    },
    {
      id: 'proj-5',
      title: 'Crop & Seed Quality Analyzer',
      slug: 'crop-seed-analyzer',
      short_desc: 'Automated crop and seed disease detection system using computer vision image classification.',
      detailed_desc:
        'Computer vision system designed to inspect crop and seed sample images, automatically classifying disease types and assigning quality ranks.',
      problem_statement: 'Manual seed inspection is labor-intensive and prone to subjective error.',
      solution_statement: 'Trained Convolutional Neural Network (CNN) models for ordinal disease ranking.',
      contribution: 'Collected dataset, trained PyTorch classification models, and deployed prediction endpoint.',
      image_url: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?auto=format&fit=crop&q=80&w=800',
      github_url: 'https://github.com/dhananjay97mki',
      live_demo_url: '#',
      tech_stack: ['Python', 'PyTorch', 'OpenCV', 'Streamlit', 'Scikit-Image'],
      category: 'AI & ML',
      featured: false,
      sort_order: 5,
      is_published: true,
      date: '2023',
    },
    {
      id: 'proj-6',
      title: 'App Store Review Sentiment Analyzer',
      slug: 'app-store-review-analyzer',
      short_desc: 'Extracts product insights and detects spam in noisy app reviews using Transformer NLP models.',
      detailed_desc:
        'NLP analysis engine that ingests thousands of app store reviews, filtering out spam and categorizing user feedback by feature, sentiment score, and urgency.',
      problem_statement: 'Product managers spend hours sifting through unorganized app feedback.',
      solution_statement: 'Fine-tuned Hugging Face sentiment classifiers with customized spam detection pipelines.',
      contribution: 'Developed NLP preprocessing, topic clustering, and data visualization dashboard.',
      image_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800',
      github_url: 'https://github.com/dhananjay97mki',
      live_demo_url: '#',
      tech_stack: ['Python', 'Transformers', 'Hugging Face', 'Pandas', 'React'],
      category: 'Data Science',
      featured: false,
      sort_order: 6,
      is_published: true,
      date: '2023',
    },
  ],
  experiences: [
    {
      id: 'exp-1',
      title: 'B.Tech in Artificial Intelligence',
      organization: 'Priyadarshini J. L. College of Engineering (PJLCE), Nagpur',
      location: 'Nagpur, India',
      start_date: '2021',
      end_date: '2025',
      is_current: true,
      description: 'Specializing in Artificial Intelligence, Deep Learning, Natural Language Processing, and Software Engineering principles.',
      category: 'Education',
      sort_order: 1,
      is_published: true,
    },
    {
      id: 'exp-2',
      title: 'B.S. in Data Science & Applications',
      organization: 'Indian Institute of Technology Madras (IIT Madras)',
      location: 'Chennai / Online',
      start_date: '2022',
      end_date: 'Present',
      is_current: true,
      description: 'Coursework in Machine Learning, Statistical Inference, Database Management, and Big Data Analytics.',
      category: 'Education',
      sort_order: 2,
      is_published: true,
    },
    {
      id: 'exp-3',
      title: 'Technical Presentation - 1st Rank Winner',
      organization: 'PJLCE Technical Fest',
      location: 'Nagpur, India',
      start_date: '2024',
      end_date: '2024',
      is_current: false,
      description: 'Secured 1st Rank for presenting AI-driven summarization and 3D memory palace educational platforms.',
      category: 'Presentation',
      sort_order: 3,
      is_published: true,
    },
    {
      id: 'exp-4',
      title: 'AI & Data Science Symposium Presenter',
      organization: 'IIT Madras',
      location: 'Chennai, India',
      start_date: '2024',
      end_date: '2024',
      is_current: false,
      description: 'Selected to present project research on NLP Transformer applications to an audience of faculty and industry leaders.',
      category: 'Presentation',
      sort_order: 4,
      is_published: true,
    },
  ],
  resumes: [
    {
      id: 'res-1',
      title: 'Dhananjay Moundekar - Primary Resume',
      description: 'Latest updated software engineering & AI developer resume (PDF format)',
      file_url: '/resume.pdf',
      type: 'resume',
      is_published: true,
      updated_at: '2025-01-15',
    },
    {
      id: 'res-2',
      title: 'Dhananjay Moundekar - Academic CV',
      description: 'Comprehensive academic and research CV including coursework and projects',
      file_url: '/resume.pdf',
      type: 'cv',
      is_published: true,
      updated_at: '2025-01-15',
    },
  ],
  socialLinks: [
    { id: 'soc-1', platform: 'GitHub', url: 'https://github.com/dhananjay97mki', icon: 'github', sort_order: 1, is_published: true },
    { id: 'soc-2', platform: 'LinkedIn', url: 'https://www.linkedin.com/in/dhananjay-moundekar-ba6b46286', icon: 'linkedin', sort_order: 2, is_published: true },
    { id: 'soc-3', platform: 'WhatsApp', url: 'https://wa.me/917875654030', icon: 'message-square', sort_order: 3, is_published: true },
    { id: 'soc-4', platform: 'Email', url: 'mailto:dhanjanjaymoundekar1244@gmail.com', icon: 'mail', sort_order: 4, is_published: true },
  ],
};
